# Generated by Django 3.0.3 on 2020-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('blood_type', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=26)),
                ('last_time_donated', models.DateField()),
                ('can_donate', models.CharField(max_length=10)),
            ],
        ),
    ]
