# Generated by Django 3.0.3 on 2020-10-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donors',
            new_name='Donor',
        ),
    ]
