# Generated by Django 3.0.3 on 2020-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0003_auto_20201021_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('location', models.CharField(max_length=26)),
                ('units_needed', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_time_donated',
            field=models.DateField(default='2020-11-01'),
        ),
    ]
