# Generated by Django 3.0.3 on 2020-11-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0004_auto_20201101_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_time_donated',
            field=models.DateField(default='2020-11-16'),
        ),
    ]
