# Generated by Django 3.0.3 on 2020-11-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0006_auto_20201116_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='x_location',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='y_location',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='x_location',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='y_location',
            field=models.FloatField(),
        ),
    ]
