# Generated by Django 3.0.3 on 2020-11-19 16:06

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0008_auto_20201116_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_time_donated',
            field=models.DateField(default='2020-11-19'),
        ),
    ]
