# Generated by Django 3.0.3 on 2020-11-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0009_auto_20201119_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='x_location',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='y_location',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='x_location',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='y_location',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
    ]
