# Generated by Django 3.0.3 on 2020-12-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0010_auto_20201119_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_time_donated',
            field=models.DateField(default='2020-08-22'),
        ),
    ]
