# Generated by Django 3.0.3 on 2020-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0011_auto_20201205_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='hospital',
            field=models.CharField(default='hosp', max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='users_confirmations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_time_donated',
            field=models.DateField(default='2020-08-24'),
        ),
    ]
