# Generated by Django 3.0.3 on 2020-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonation', '0013_auto_20201207_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='can_donate',
        ),
    ]
